image: debian/buster
packages:
    - wget
    - lsb-release
    - apt-transport-https
    - ca-certificates
    - sudo
tasks:
- setup: |
    wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
    apt update
    apt purge -y apache2
    apt install -y php7.4 php7.4-{bcmath,bz2,intl,gd,mbstring,mysql,zip,curl}
    apt autoremove -y
    export WEBHOOK_URL="$(cat ~/.webhook_url)"
- test: |
    cd discord.php
    echo $WEBHOOK_URL
    php discord-php test
- build: |
    cd discord.php
    php discord-php build --build-version=$(git rev-parse --short HEAD)
secrets:
    - 12bc9b7b-ecfb-4633-95ed-af83de742135