image: debian/buster
artifacts:
  - /home/build/discord.php/builds/discord-php
packages:
    - wget
    - lsb-release
    - apt-transport-https
    - ca-certificates
    - zip
    - unzip
tasks:
- setup: |
    sudo wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
    echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
    sudo apt-get update > /dev/null
    sudo apt-get purge -y apache2 > /dev/null
    sudo apt-get install -y php7.4 php7.4-{bcmath,bz2,intl,gd,mbstring,mysql,zip,curl,xml} > /dev/null
    sudo apt-get autoremove -y > /dev/null
    sudo apt-get upgrade -y > /dev/null
    wget https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer -O - -q | sudo php -- --install-dir=/usr/local/bin --filename=composer
    cd discord.php
    composer install --no-progress
    export WEBHOOK_URL="$(cat ~/.webhook_url)"
- test: |
    cd discord.php
    echo $WEBHOOK_URL
    php discord-php test
- build: |
    cd discord.php
    php discord-php app:build -n --build-version="$(git rev-parse --short HEAD)"
- test-webhook: |
    cd discord.php
    ./builds/discord-php webhook:send --text "Test Text"
secrets:
    - 21f12a6c-9035-47bc-a610-36e93c413269
    - 12bc9b7b-ecfb-4633-95ed-af83de742135